language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 5.6
          env: DEPENDENCIES=dev

before_script:
    - composer self-update
    - if [ "$TRAVIS_PHP_VERSION" = "5.6" ] && [ "$DEPENDENCIES" != "dev" ]; then wget http://get.sensiolabs.org/php-cs-fixer.phar; fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
    - composer install

script:
    - vendor/bin/behat
    - vendor/bin/phpunit
    - if [ "$TRAVIS_PHP_VERSION" = "5.6" ] && [ "$DEPENDENCIES" != "dev" ]; then php php-cs-fixer.phar fix --no-interaction --dry-run --diff -vvv; fi;
