language: php

sudo: false

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: nightly
        - php: hhvm-nightly
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

before_script: composer self-update
install: composer install
script: vendor/bin/behat
