language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.5
    - 7.0
    - nightly
    - hhvm

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*@dev
        - php: 5.6
          env: SYMFONY_VERSION="3.0.*@dev"
        - php: 7.0

    allow_failures:
        - php: 7.0
        - php: nightly
        - env: SYMFONY_VERSION=2.8.*@dev
        - env: SYMFONY_VERSION="3.0.*@dev"

before_install:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then
          composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update;
      fi;

install:
    - composer update --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit
    - vendor/bin/behat
