language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - composer self-update
    - wget http://get.sensiolabs.org/php-cs-fixer.phar

install:
    - composer install

script:
    - vendor/bin/behat
    - vendor/bin/phpunit
    - php php-cs-fixer.phar fix --no-interaction --dry-run --diff -vvv
