name: CI

on:
  push:
  pull_request:

env:
  COMPOSER_ALLOW_SUPERUSER: '1' # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-alpine
    strategy:
      matrix:
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4-rc'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install system packages
        run: |
          apk add \
            unzip \
      - name: Install mongodb PHP extension
        if: matrix.php != '7.1'
        run: |
          apk add $PHPIZE_DEPS
          pecl install mongodb-1.5.5
          docker-php-ext-enable mongodb
      - name: Disable PHP memory limit
        run: echo 'memory_limit=-1' >> /usr/local/etc/php/php.ini
      - name: Install Composer
        run: wget -qO - https://raw.githubusercontent.com/composer/getcomposer.org/fb22b78362d31c0d2bf516d1f8cdfd2745caa431/web/installer | php -- --install-dir=/usr/local/bin --filename=composer --quiet
      - name: Remove Doctrine MongoDB ODM
        if: matrix.php == '7.1'
        run: |
          composer remove --dev --no-progress --no-update --ansi \
            doctrine/mongodb-odm \
            doctrine/mongodb-odm-bundle \
      - name: Update project dependencies
        run: composer update --no-progress --no-suggest --ansi
      - name: Clear test app cache
        run: tests/Fixtures/app/console cache:clear --ansi
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --colors=always

  phpunit-lowest-deps:
    name: PHPUnit (PHP ${{ matrix.php }}) (lowest dependencies)
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-alpine
    strategy:
      matrix:
        php:
          - '7.3'
          - '7.4-rc'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install system packages
        run: |
          apk add \
            unzip \
      - name: Install mongodb PHP extension
        if: matrix.php != '7.1'
        run: |
          apk add $PHPIZE_DEPS
          pecl install mongodb-1.5.5
          docker-php-ext-enable mongodb
      - name: Disable PHP memory limit
        run: echo 'memory_limit=-1' >> /usr/local/etc/php/php.ini
      - name: Install Composer
        run: wget -qO - https://raw.githubusercontent.com/composer/getcomposer.org/fb22b78362d31c0d2bf516d1f8cdfd2745caa431/web/installer | php -- --install-dir=/usr/local/bin --filename=composer --quiet
      - name: Remove Doctrine MongoDB ODM
        if: matrix.php == '7.1'
        run: |
          composer remove --dev --no-progress --no-update --ansi \
            doctrine/mongodb-odm \
            doctrine/mongodb-odm-bundle \
      - name: Update project dependencies
        run: composer update --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi
      - name: Clear test app cache
        run: tests/Fixtures/app/console cache:clear --ansi
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --colors=always

  phpunit-no-deprecations:
    name: PHPUnit (PHP ${{ matrix.php }}) (no deprecations)
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-alpine
    strategy:
      matrix:
        php:
          - '7.3'
      fail-fast: false
    env:
      SYMFONY_DEPRECATIONS_HELPER: max[total]=5 # 5 deprecation notices from FOSUserBundle
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install system packages
        run: |
          apk add \
            unzip \
      - name: Install mongodb PHP extension
        if: matrix.php != '7.1'
        run: |
          apk add $PHPIZE_DEPS
          pecl install mongodb-1.5.5
          docker-php-ext-enable mongodb
      - name: Disable PHP memory limit
        run: echo 'memory_limit=-1' >> /usr/local/etc/php/php.ini
      - name: Install Composer
        run: wget -qO - https://raw.githubusercontent.com/composer/getcomposer.org/fb22b78362d31c0d2bf516d1f8cdfd2745caa431/web/installer | php -- --install-dir=/usr/local/bin --filename=composer --quiet
      - name: Remove Doctrine MongoDB ODM
        if: matrix.php == '7.1'
        run: |
          composer remove --dev --no-progress --no-update --ansi \
            doctrine/mongodb-odm \
            doctrine/mongodb-odm-bundle \
      - name: Update project dependencies
        run: composer update --no-progress --no-suggest --ansi
      - name: Clear test app cache
        run: tests/Fixtures/app/console cache:clear --ansi
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --colors=always
        continue-on-error: true
